### ISSUE TITLE
Kanban Setup

### ISSUE THREAD

**Issue by TEMESGEN-G25** [NatiG25/catalog-of-my-things#34]
**Github project**: https://github.com/NatiG25/catalog-of-my-things/projects?type=new

**Note**: There are 3 members in this team.

Team member #1: @HammadSiddique (Student - A)
Team member #2: @NatiG25 (Student - B)
Team member #3: @GOlivierNation (Student - C)

**Comment by Kingstalux** [comment]
Hi @team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :x: 

- [x] Kindly provide a link to your GitHub project and not the repo :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by TEMESGEN-G25** [comment]
@Kingstalux Thank you. I'll change it right away.

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @NatiG25, @GOlivierNation and @HammadSiddique,

Good job so far!
✔️ Kanban is well set up
✔️ Tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] You Kanban board is missing the `In review` column. Kindly include that as well

- [x] Kindly ensure all your tasks are assigned
  
  ![assi-task](https://user-images.githubusercontent.com/36542986/183406489-d07b79e7-6889-4fdd-9dcd-fea68f30bfad.jpg)

- [x] Kindly include a description of your task.

  ![game-c](https://user-images.githubusercontent.com/36542986/183406582-c57b09b7-4a4b-4ad4-8e16-758a5f54c6ac.jpg)

- [x] I can't seem to find any task that caters to this group task requirement

  ![imp-start](https://user-images.githubusercontent.com/36542986/183406760-641b082a-81f8-4574-91e9-50ff78596da9.jpg)

- [x] Student C (@GOlivierNation) does not seem to have tasks that take of these requirements.

  ![stud-c](https://user-images.githubusercontent.com/36542986/183406912-8b0c3cc8-3407-4326-9982-36b9f21f8eee.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HammadSiddique** [comment]
### We have implemented the requested changes:

- Added a review column on the kanban board.
- Assigned issue #33 to student B (@NatiG25 )
- Added description to issue #3 
- Startup actions tasks are catered to in issue #32 
- `add_item` method was already listed in issue #14 
- `can_be_archived?()` method was already listed in issue #16

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @NatiG25, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
